import os
os.system("clear")
print("Wine Installer")
print("A tool for installing Wine on any PIOS System running PIOS Bullseye")
print("Press Enter To Install")
input("")
os.system("clear")
os.system("cat LICENSE")
print("10 second timeout to agree")
import time
time.sleep(10)
os.system("clear")
os.system("cat LICENSE")
print("Click enter to aggree")
input("")
os.system("sudo dpkg --add-architecture i386 && sudo wget -nc -O /usr/share/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key")
os.system("sudo wget -nc -P /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/debian/dists/bullseye/winehq-bullseye.sources && sudo apt update && sudo apt install --install-recommends winehq-stable")
print("Wine has been installed! Restarting in 10 seconds...")
time.sleep(10)
os.system("shutdown -r now")
